# Generated by Django 6.0.4 on 2026-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_personal_doc_brain_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('n8n', 'n8n Agent Workflow'), ('langchain', 'LangChain Agent'), ('ai_studio', 'Google AI Studio Media'), ('ml', 'Machine Learning (scikit-learn)'), ('django', 'Django Web App'), ('personal', 'Personal Build'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
